apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'
urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_token/', views.course_token, name='course_token'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
    # path('more/', include('apps.more.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/course/models.py
from django.db import models


# 课程分类
class CourseCategory(models.Model):
    name = models.CharField(max_length=100)


# 课程讲师
class Teacher(models.Model):
    # 姓名
    username = models.CharField(max_length=100)
    # 头像
    avatar = models.URLField()
    # 职务
    jobtitle = models.CharField(max_length=100)
    # 简介
    profile = models.TextField()



class Course(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey('CourseCategory',on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey('Teacher',on_delete=models.DO_NOTHING)
    # 视频链接
    video_url = models.URLField()
    # 封面图链接
    cover_url = models.URLField()
    price = models.FloatField()
    # 时长
    duration = models.IntegerField()
    # 简介
    profile = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)

apps/course/views.py
from django.shortcuts import render
from apps.course.models import Course
from django.conf import settings
import time,os,hmac,hashlib
from utils import restful


def course_index(request):
    courses = Course.objects.all()
    context = {
        'courses': courses
    }
    return render(request, 'course/course_index.html', context=context)


def course_detail(request, course_id):
    course = Course.objects.get(pk=course_id)
    context = {
        'course': course
    }
    return render(request, 'course/course_detail.html', context=context)


# 生成百度云token
def course_token(request):
    # video：是视频文件的完整链接
    file = request.GET.get('video')

    expiration_time = int(time.time()) + 2 * 60 * 60

    USER_ID = settings.BAIDU_CLOUD_USER_ID
    USER_KEY = settings.BAIDU_CLOUD_USER_KEY

    # file=http://hemvpc6ui1kef2g0dd2.exp.bcevod.com/mda-igjsr8g7z7zqwnav/mda-igjsr8g7z7zqwnav.m3u8
    extension = os.path.splitext(file)[1]
    media_id = file.split('/')[-1].replace(extension, '')

    # unicode->bytes=unicode.encode('utf-8')bytes
    key = USER_KEY.encode('utf-8')
    message = '/{0}/{1}'.format(media_id, expiration_time).encode('utf-8')
    signature = hmac.new(key, message, digestmod=hashlib.sha256).hexdigest()
    token = '{0}_{1}_{2}'.format(signature, USER_ID, expiration_time)
    return restful.result(data={'token': token})

front/templates/course/course_detail.html
{% extends 'base/front_base.html' %}

{% block title %}
    视频详情 | 子午
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/course/course_detail.min.css' %}">
    <script src="{% static 'videojs/video.min.js' %}"></script>
    <script src="{% static 'videojs/videojs-contrib-hls.min.js' %}"></script>
    <script src="{% static 'videojs/videojs-contrib-quality-levels.min.js' %}"></script>
    <script type="text/javascript" src="https://cdn.bdstatic.com/jwplayer/latest/cyberplayer.js"></script>

    <script src="{% static 'js/course_detail.min.js' %}"></script>
{% endblock %}

{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="nav-container">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li class="active"><a href="">最新课堂</a></li>
                    <li><a href="">学习</a></li>
                    <li><a href="">生活</a></li>
                    <li><a href="">娱乐</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <div class="course-wrapper">
                <div class="course-info">
                    <p class="course-title">{{ course.title }}</p>
                    <div class="price-group">
                        <div class="share-group">
                            <span class="title">分享至：</span>
                            <a href="" class="weixin"></a>
                            <a href="" class="weibo"></a>
                        </div>
                        <div class="buy-group">
                            <!-- <span class="price">49元</span>
                             <a href="" class="buy-btn">立即购买</a>  -->
                            <span class="free">免费</span>
                        </div>
                    </div>
                </div>
                <div class="video-group">
                    <span id="video-info" data-video-url="{{ course.video_url }}"
                          data-cover-url="{{ course.cover_url }}" hidden></span>
                    <div id="playercontainer"></div>
                </div>
            </div>
            <div class="bottom-wrapper">
                <div class="course-detail-wrapper">
                    <div class="item-group">
                        <p class="item-title">人物</p>
                        <div class="teacher-group">
                            <div class="avatar-group">
                                <img src="{{ course.teacher.avatar }}" alt="">
                            </div>
                            <div class="author-info">
                                <p class="teacher-name">{{ course.teacher.username }}</p>
                                <p class="teacher-desc">
                                    {{ course.teacher.jobtitle }}
                                </p>
                            </div>
                        </div>
                        <p class="item-title">简介</p>
                        <p class="item-content">
                            {{ course.profile|safe }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/course/course_index.html
{% extends 'base/front_base.html' %}

{% block title %}
    视频 | 子午
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/course/course.min.css' %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="nav-container">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li class="active"><a href="javascript:void (0)">最新课堂</a></li>
                    <li><a href="javascript:void (0)">学习</a></li>
                    <li><a href="javascript:void (0)">生活</a></li>
                    <li><a href="javascript:void (0)">娱乐</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <ul class="course-list">
                {% for course in courses %}
                    <li>
                        <a href="{% url 'course:course_detail'  course_id=course.pk %}">
                            <div class="thumbnail-group">
                                <img src="{{ course.cover_url }}" alt="">
                            </div>
                            <div class="course-info">
                                <p class="title">{{ course.title }}</p>
                                <p class="author">{{ course.teacher.username }}</p>
                                <p class="price-group">
                                    <span class="free">免费</span>
                                </p>
                            </div>
                        </a>
                    </li>
                {% endfor %}


                <li style="background: #F2F2F2;"></li>
                <li style="background: #F2F2F2;"></li>
            </ul>
        </div>
    </div>
{% endblock %}