apps/cms/urls.py
from django.urls import path
from . import views, course_views, staff_views

app_name = 'cms'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),
    path('banners/', views.banners, name='banners'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
]

# 课程管理
urlpatterns += [
    path('pub_course/', course_views.PubCourseView.as_view(), name='pub_course'),
]

# 权限管理
urlpatterns += [
    path('staff/', staff_views.index, name='staff_index'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('search/', views.search, name='search'),
    path('list/', views.news_list, name='news_list'),
    path('pub_comment/', views.pub_comment, name='pub_comment'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('cache/', views.cache_test, name='cache'),
    path('register/', views.register, name='register'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
    # path('more/', include('apps.more.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/cms/models.py
from django.db import models

# Create your models here.

apps/course/models.py
from django.db import models


# 课程分类
class CourseCategory(models.Model):
    name = models.CharField(max_length=100)


# 课程讲师
class Teacher(models.Model):
    # 姓名
    username = models.CharField(max_length=100)
    # 头像
    avatar = models.URLField()
    # 职务
    jobtitle = models.CharField(max_length=100)
    # 简介
    profile = models.TextField()



class Course(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey('CourseCategory',on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey('Teacher',on_delete=models.DO_NOTHING)
    # 视频链接
    video_url = models.URLField()
    # 封面图链接
    cover_url = models.URLField()
    price = models.FloatField()
    # 时长
    duration = models.IntegerField()
    # 简介
    profile = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)

apps/news/models.py
from django.db import models


class NewsCategory(models.Model):
    name = models.CharField(max_length=100)


class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField(null=True, blank=True, default='http://cdn.shiqianlong.top/ziwu.png')
    content = models.TextField()
    category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
    pub_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    user = models.ForeignKey('xfzauth.User',on_delete=models.CASCADE)
    content = models.TextField()
    news = models.ForeignKey('News',on_delete=models.CASCADE,related_name='comments')
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    priority = models.IntegerField()
    thumbnail = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['priority']

apps/cms/forms.py
from django import forms
from apps.forms import FormMixin
from apps.news.models import News, Banner
from apps.course.models import Course


class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField(error_messages={'required': '必须传入分类id'})
    name = forms.CharField(max_length=100)


class WriteNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'pub_time', 'author']


class AddBannerForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banner
        fields = ['thumbnail', 'priority', 'link_to']


class EditBannerForm(forms.ModelForm,FormMixin):
    pk = forms.IntegerField()
    class Meta:
        model = Banner
        fields = ['thumbnail','priority','link_to']


class EditNewsForm(forms.ModelForm,FormMixin):
    category = forms.IntegerField()
    pk = forms.IntegerField()
    class Meta:
        model = News
        exclude = ['category','author','pub_time']


class PubCourseForm(forms.ModelForm,FormMixin):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()
    class Meta:
        model = Course
        exclude = ['category','teacher']

apps/cms/views.py
from django.shortcuts import render
# 验证是否是员工，如果不是则定位到其他页面
from django.contrib.admin.views.decorators import staff_member_required
from django.views import View
from django.views.decorators.http import require_POST, require_GET
from apps.news.models import NewsCategory, News
from utils import restful
from .forms import EditNewsCategoryForm, WriteNewsForm, EditNewsForm
import os
from django.conf import settings
import qiniu
from django.core.paginator import Paginator
from datetime import datetime
from django.utils.timezone import make_aware
from urllib import parse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required


def login_view(request):
    return render(request, 'cms/login.html')


# 员工验证器
@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')


@method_decorator(permission_required(perm="news.add_news", login_url='/'), name='dispatch')
class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()

        context = {
            'categories': categories
        }
        return render(request, 'cms/write.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            content = form.cleaned_data.get('content')
            thumbnail = form.cleaned_data.get('thumbnail')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title, desc=desc, content=content, thumbnail=thumbnail, category=category,
                                author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_GET
@permission_required(perm="news.add_newscategory",login_url='/')
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
@permission_required(perm="news.add_newscategory",login_url='/')
def add_news_category(request):
    name = request.POST.get('name')
    exist = NewsCategory.objects.filter(name=name)
    if not exist:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已存在')


@require_POST
@permission_required(perm="news.change_newscategory",login_url='/')
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='该分类不存在')
    else:
        return restful.params_error(message=form.get_errors())


@require_POST
@permission_required(perm="news.delete_newscategory",login_url='/')
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.params_error(message='该分类不存在！')


@require_POST
@staff_member_required(login_url='index')
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)

    # 拼接url,  http://127.0.0.1:8000/media/001.png
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url})


@require_GET
@staff_member_required(login_url='index')
def qntoken(request):
    access_key = settings.QINIU_ACCESS_KEY
    secret_key = settings.QINIU_SECRET_KEY
    q = qiniu.Auth(access_key, secret_key)
    bucket = settings.QINIU_BUCKET_NAME
    token = q.upload_token(bucket)
    return restful.result(data={'token': token})



def banners(request):
    return render(request, 'cms/banners.html')


def news_list(request):
    categories = NewsCategory.objects.all()
    newses = News.objects.select_related('category', 'author').all()
    context = {
        'categories': categories,
        'newses': newses
    }
    return render(request, 'cms/news_list.html', context=context)


@method_decorator(permission_required(perm="news.change_news", login_url='/'), name='dispatch')
class NewsListView(View):
    def get(self, request):
        page = int(request.GET.get('p', 1))
        categories = NewsCategory.objects.all()
        newses = News.objects.select_related('category', 'author')

        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0) or 0)

        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')
            else:
                start_date = datetime(year=2020, month=1, day=1)
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
            newses = newses.filter(category_id=category_id)

        paginator = Paginator(newses, 10)
        page_obj = paginator.page(page)

        paginator_data = self.get_pagination_data(paginator, page_obj)

        context = {
            'categories': categories,
            'newses': page_obj.object_list,
            'page_obj': page_obj,
            'category_id': category_id,
            'url_query': '&' + parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or ''
            }),
            'title': title,
            'start': start,
            'end': end
        }

        context.update(paginator_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=10):
        current_page = page_obj.number
        num_pages = paginator.num_pages
        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_pages = range(current_page - around_count, current_page)
            left_has_more = True

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_pages = range(current_page + 1, current_page + around_count + 1)
            right_has_more = True

        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages,
        }


@method_decorator(permission_required(perm="news.change_news",login_url='/'),name='dispatch')
class EditNewsView(View):
    def get(self, request):
        news_id = request.GET.get('news_id')
        news = News.objects.get(pk=news_id)
        category = NewsCategory.objects.all()

        context = {
            'news': news,
            'categories': category
        }
        return render(request, 'cms/write.html', context=context)

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            pk = form.cleaned_data.get('pk')
            category = NewsCategory.objects.get(pk=category_id)
            print('=' * 30)
            print(type(category))
            print(category)
            print('=' * 30)
            News.objects.filter(pk=pk).update(title=title, desc=desc, thumbnail=thumbnail, content=content,
                                              category=category)
            return restful.ok()
        else:
            return restful.params_error(form.get_errors())


@require_POST
@permission_required(perm="news.delete_news",login_url='/')
def delete_news(request):
    news_id = request.POST.get('news_id')
    News.objects.filter(pk=news_id).delete()
    return restful.ok()

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}|子午管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">

    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    {% block head %}

    {% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <a href="/" class="logo">
            <span class="logo-mini"><b>CMS</b></span>
            <span class="logo-lg">子午管理系统</span>
        </a>

        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="http://cdn.shiqianlong.top/avatar.png" class="user-image" alt="User Image">
                            <span class="hidden-xs">子午</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="http://cdn.shiqianlong.top/avatar.png" class="img-circle" alt="User Image">

                                <p>
                                    联合开发部
                                    <small>子午</small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>

        </nav>
    </header>
    <aside class="main-sidebar">
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="搜索">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                  <i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>


                {% if perms.news.change_news %}
                    <li class="header">新闻管理</li>
                    <li>
                        <a href="{% url 'cms:write_news' %}">
                            <i class="fa fa-edit"></i>
                            <span>发布文章</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:news_category' %}">
                            <i class="fa fa-tags"></i>
                            <span>文章分类</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:banners' %}">
                            <i class="fa fa-window-restore"></i>
                            <span>轮播图</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'cms:news_list' %}">
                            <i class="fa fa-list"></i>
                            <span>文章管理</span>
                        </a>
                    </li>
                {% endif %}

                {% if perms.course.change_course %}
                    <li class="header">视频管理</li>
                    <li>
                        <a href="{% url 'cms:pub_course' %}">
                            <i class="fa fa-tv"></i>
                            <span>发布视频</span>
                        </a>
                    </li>
                {% endif %}


                {% if user.is_superuser %}
                    <li class="header">成员管理</li>
                    <li>
                        <a href="{% url 'cms:staff_index' %}">
                            <i class="fa fa-group"></i>
                            <span>成员管理</span>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </section>
    </aside>

    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}

            {% endblock %}
        </section>

        <section class="content">
            {% block content %}

            {% endblock %}
        </section>
    </div>

    <footer class="main-footer">
        子午工作室
    </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
    首页
{% endblock %}

{% block content-header %}
    <h1>子午管理系统</h1>
{% endblock %}

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}
{% load news_filters %}


{% block head %}
    {#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"#}
    {#          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>

    <style type="text/css">
        .left-group {
            margin-right: 20px;
        }
    </style>
{% endblock %}

{% block title %}
    文章列表
{% endblock %}

{% block content-header %}
    <h1>文章列表管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <form action="" class="form-inline" method="get">
                        <div class="form-group left-group">
                            <label for="">时间：</label>
                            {% if start %}
                                <input type="text" class="form-control" id="startPicker" name="start" placeholder="起始时间"
                                       value="{{ start }}" readonly>
                            {% else %}
                                <input type="text" class="form-control" id="startPicker" name="start" placeholder="起始时间"
                                       readonly>
                            {% endif %}
                            <span>——</span>
                            {% if end %}
                                <input type="text" class="form-control" id="endPicker" name="end" placeholder="结束时间"
                                       value="{{ end }}" readonly>
                            {% else %}
                                <input type="text" class="form-control" id="endPicker" name="end" placeholder="结束时间"
                                       readonly>
                            {% endif %}
                        </div>
                        <div class="form-group left-group">
                            <label for="">标题：</label>
                            {% if title %}
                                <input type="text" class="form-control" placeholder="关键字" name="title"
                                       value="{{ title }}">
                            {% else %}
                                <input type="text" class="form-control" placeholder="关键字" name="title">
                            {% endif %}
                        </div>
                        <div class="form-group left-group">
                            <label for="">分类：</label>
                            <select name="category" id="" class="form-control">
                                {% if category_id == 0 %}
                                    <option value="0" selected>所有分类</option>
                                {% else %}
                                    <option value="0">所有分类</option>
                                {% endif %}
                                {% for category in categories %}
                                    {% if category_id == category.pk %}
                                        <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.pk }}">{{ category.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary left-group">查询</button>
                            <a href="{% url 'cms:news_list' %}">清除查询</a>
                        </div>
                    </form>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>标题</th>
                            <th>分类</th>
                            <th>发布时间</th>
                            <th>作者</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for news in newses %}
                            <tr>
                                <td><a href="{% url 'news:news_detail' news_id=news.pk %}"
                                       target="_blank">{{ news.title }}</a></td>
                                <td>{{ news.category.name }}</td>
                                <td>{{ news.pub_time|time_format }}</td>
                                <td>{{ news.author.username }}</td>
                                <td>
                                    <a href="{% url 'cms:edit_news' %}?news_id={{ news.pk }}" class="btn btn-info btn-xs" target="_blank">编辑</a>
                                    <button class="btn btn-danger btn-xs delete-btn delete-btn" data-news-id="{{ news.pk }}">删除</button>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                    <ul class="pull-right left-group">
                        {% for article in articles %}
                            <li>{{ article.title }}</li>
                        {% endfor %}
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li>
                                        <a href="?p={{ page_obj.previous_page_number }}{{ url_query }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="disabled">
                                        <a href="javascript:void(0)" aria-label="Previous">
                                            <span aria-hidden="true">上一页</span>
                                        </a>
                                    </li>
                                {% endif %}


                                {% if left_has_more %}
                                    <li><a href="?p=1">1</a></li>
                                    <li><a href="javascript:void (0)">...</a></li>
                                {% endif %}

                                {#            左边的页面#}
                                {% for left_page in left_pages %}
                                    <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                                {% endfor %}

                                {#            当前的页面#}
                                <li class="active"><a
                                        href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                                {#            右边的页面#}
                                {% for right_page in right_pages %}
                                    <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                                {% endfor %}

                                {% if right_has_more %}
                                    <li><a href="javascript:void (0)">...</a></li>
                                    <li><a href="?p={{ num_pages }}">{{ num_pages }}</a></li>
                                {% endif %}

                                {% if page_obj.has_next %}
                                    <li>
                                        <a href="?p={{ page_obj.next_page_number }}{{ url_query }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    </li>

                                {% else %}
                                    <li class="disabled">
                                        <a href="javascript:void (0)" aria-label="Next">
                                            <span aria-hidden="true">下一页</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </ul>
                    <p class="pull-left">第{{ current_page }}页/总共{{ num_pages }}页</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}