apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('cache/', views.cache_test, name='cache'),
    path('register/', views.register, name='register'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
    # path('more/', include('apps.more.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

front/templates/common/auth.html
{% extends 'base/front_base.html' %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <script src="{% static 'js/auth.min.js' %}"></script>
{% endblock %}

{% block main %}
    <div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <div class="close-btn">
                    <span class="icon-close iconfont"></span>
                </div>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-group">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="请输入手机号码" name="telephone">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" placeholder="请输入密码" name="password">
                            </div>
                            <div class="input-group">
                                <label for="" class="remember-label">
                                    <input type="checkbox" value="1" name="remember">
                                    记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="请输入用户名">
                            </div>
{#                            <div class="input-group">#}
{#                                <div class="short-input-group">#}
{#                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">#}
{#                                </div>#}
{#                                <div class="input-group-addon">#}
{#                                    <img src="{% url 'xfzauth:img_captcha' %}" alt="" class="img_captcha">#}
{#                                </div>#}
{#                            </div>#}
                            <div class="input-group">
                                <input type="password" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms_captcha">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" value="立即注册" class="submit-btn">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/common/sidebar.html
<div class="side-wrapper">
                <div class="title-group">
                    <span class="title">网站公告</span>
                    <span class="more"><a href="">更多</a></span>
                </div>
                <div class="advertise-group">
                    <a href="">
                        <img src="http://cdn.shiqianlong.top/web1.jpg" alt="">
                    </a>
                </div>
                <div class="platform-group">
                    <div class="title-group">
                        <span class="title">关注我们</span>
                    </div>
                    <div class="focus-group">
                        <ul class="left-group">
                            <li class="gitee">
                                <i class="icon-mayun iconfont"></i>
                                <a href="https://gitee.com/shiqianlong" target="_blank">码云</a>
                            </li>
                            <li class="github">
                                <i class="icon-huaban88 iconfont"></i>
                                <a href="https://github.com/shiqianlong" target="_blank">GitHub</a>
                            </li>
                            <li class="weibo">
                                <i class="icon-weibo iconfont"></i>
                                <a href="https://weibo.com/p/1005056574236863/home?from=page_100505&mod=TAB&is_all=1#place" target="_blank">我的微博</a>
                            </li>
                        </ul>
                        <div class="right-group">
                            <p class="desc">扫码关注公众号平台"大Python"</p>
                        </div>
                    </div>
                </div>

                <div class="hot-news-group">
                    <div class="title-group">
                        <span class="title">推荐</span>
                    </div>
                    <ul class="hot-list-group">
{#                        <li>#}
{#                            <div class="left-group">#}
{#                                <p class="title">#}
{#                                    <a href="">这是一篇热门新闻，这是一篇热门新闻...</a>#}
{#                                </p>#}
{#                                <p class="more">#}
{#                                    <span class="category">python</span>#}
{#                                    <span class="pub-time">1小时前</span>#}
{#                                </p>#}
{#                            </div>#}
{#                            <div class="right-group">#}
{#                                <a href="">#}
{#                                    <img src="{% static 'images/4.jpg' %}" alt="">#}
{#                                </a>#}
{#                            </div>#}
{#                        </li>#}
                    </ul>
                </div>
            </div>