apps/cms/urls.py
from django.urls import path
from . import views, course_views, staff_views

app_name = 'cms'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),
    path('banners/', views.banners, name='banners'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
]

# 课程管理
urlpatterns += [
    path('pub_course/', course_views.PubCourseView.as_view(), name='pub_course'),
]

# 权限管理
urlpatterns += [
    path('staff/', staff_views.index, name='staff_index'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
]

apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'
urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_token/', views.course_token, name='course_token'),
]

apps/more/urls.py
from django.urls import path
from . import views

app_name = 'more'
urlpatterns = [
    path('more_index/',views.more_index,name='more_index'),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('search/', views.search, name='search'),
    path('list/', views.news_list, name='news_list'),
    path('pub_comment/', views.pub_comment, name='pub_comment'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.xfzauth.urls')),
    path('course/', include('apps.course.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
    # path('more/', include('apps.more.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1980187_y17r6lhijc.css">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <script src="{% static 'js/front_base.min.js' %}"></script>
    {% block header %}

    {% endblock %}

</head>
<body>
<header class="header">
    <div class="container">
        <div class="logo-box">
            <a href="/"></a>
        </div>

        <ul class="nav">
            <li class="active"><a href="{% url 'index' %}">文章</a></li>
            <li><a href="{% url 'course:course_index' %}" target="_blank">视频</a></li>
{#            <li><a href="{% url 'more:more_index' %}">更多</a></li>#}
            <li><a href="javascript:void (0)">更多</a></li>
            <li><a href="{% url 'news:search' %}" target="_blank">搜索</a></li>
        </ul>

        <div class="auth-box">
            <i class="icon-person_icon iconfont"></i>
            {% if user.is_authenticated %}
                <a href="" class="authenticated-box">{{ user.username }}</a>
                <div class="user-more-box">
                    <i class="triangle"></i>
                    {% if user.is_staff %}
                        <a href="{% url 'cms:index' %}">管理系统</a>
                    {% endif %}
                    <a href="{% url 'xfzauth:logout' %}">退出登录</a>
                </div>

            {% else %}
                <a href="#" class="signin-btn">登录</a> /
                <a href="#" class="signup-btn">注册</a>
            {% endif %}
        </div>
    </div>
</header>

{% block main %}

{% endblock %}

<footer class="footer">
    <div class="top-group">
        <div class="top-inner-group">
            <div class="logo-box">

            </div>
            <div class="detail-group">
                <div class="line1">
                    <ul class="links">
                        <li><a href="">关于我们</a></li>
                        <li><a href="https://www.aliyun.com/">阿里云</a></li>
                        <li><a href="https://www.baidu.com/" target="_blank">百度</a></li>
                    </ul>
                    <div class="about-us">
                        <span class="title">关于我们：</span>
                        <ul class="social-group">
                            <li class="weixin">
                                <div class="wx-qrcode"></div>
                                <i class="icon-weixin iconfont"></i>
                            </li>
                            <li class="qq">
                                <div class="qq-qrcode"></div>
                                <i class="icon-qq-icon iconfont"></i>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="line2">
                    <p class="duty">
                        免责声明：若本站收入的资源侵犯了您的权益，请联系本站及时删除其内容。
                    </p>
                </div>
                <div class="line3">

                    <div class="contact">
                        <span class="contact-adder">联系方式</span>
                        <i class="icon-mail_gaoliang iconfont">：</i>
                        <span class="email">ziwu2022@gmail.com</span>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="bottom-group">
        <p class="info">@2020 子午工作室 <a href="http://www.beian.miit.gov.cn/" style="color: #c9c9c9" target="_blank">鄂ICP备20011056号</a>
        </p>
    </div>
</footer>


<div class="mask-wrapper">
    <div class="auth-wrapper">
        <div class="close-wrapper">
            <div class="close-btn">
                <span class="icon-close iconfont"></span>
            </div>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-group">
                <div class="signin-group auth-group">
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript: void(0);" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="请输入手机号码" name="telephone">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" placeholder="请输入密码" name="password">
                        </div>
                        <div class="input-group">
                            <label for="" class="remember-label">
                                <input type="checkbox" value="1" name="remember">
                                记住我
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即登录">
                        </div>
                    </div>
                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a href="javascript: void(0);" class="switch">立即登录></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" name="username" placeholder="请输入用户名">
                        </div>
{#                        <div class="input-group">#}
{#                            <div class="short-input-group">#}
{#                                <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">#}
{#                            </div>#}
{#                            <div class="input-group-addon">#}
{#                                <img src="{% url 'xfzauth:img_captcha' %}" alt="" class="img_captcha">#}
{#                            </div>#}
{#                        </div>#}
                        <div class="input-group">
                            <input type="password" class="form-control" name="password1" placeholder="密码">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password2" placeholder="确认密码">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                            </div>
                            <div class="input-group-addon">
                                <span class="sms_captcha">发送验证码</span>
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="submit" value="立即注册" class="submit-btn">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>